name: SurvivalGames
main: me.petterroea.newsurvival.Survival
version: 0.01
authors: ['Petterroea', 'I_am_not_funny']
commands:
    start:
        desc: 'Starts the game! You need at least 2 players to do this'
        usage: 'Usage: /start'
    spectate:
        desc: 'Puts you in spectate mode. You have to do this before a game'
        usage: 'Usage: /spectate'
    tpto:
        desc: 'Teleports a spectator to a player'
        usage: 'Usage: /tpto <PLAYER>'
    alive:
        desc: 'Tells you who is still alive'
        usage: '/alive'
    sort:
        desc: 'Sorts players'
        usage: '/sort'
    deathmatch:
        desc: 'Starts deathmatch'
        usage: '/deathmatch'
    revive:
        desc: 'Revives'
        usage: '/revive <player>'